import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Cloud, LayoutDashboard, ClipboardList, Inbox, Settings, Save, RefreshCw, Plus, Trash2, Send, Search, CheckCircle2, AlertCircle } from 'lucide-react';
import './styles.css';

type AppType = { id:string; name:string; emoji:string; description:string; active:boolean; questions:string[]; roles:{onSubmit:string[];onAccept:string[];onDeny:string[];removeOnAccept:string[];removeOnDeny:string[]} };
type Config = { brand:{name:string;accent:number}; panel:{title:string;description:string;footer:string}; reviewRoleId:string; channels:Record<string,string>; messages:Record<string,string>; applicationTypes:AppType[] };
type Submission = {id:string;username:string;type:string;status:string;submittedAt:string};

const API = '/api';
const blankApp = ():AppType => ({id:`custom-${Date.now()}`,name:'New Application',emoji:'📋',description:'',active:true,questions:['What would you like us to know?'],roles:{onSubmit:[],onAccept:[],onDeny:[],removeOnAccept:[],removeOnDeny:[]}});

function Loading({saving}:{saving:boolean}) { return saving ? <span className="saving">Loading<span className="dots"></span></span> : null; }
function App(){
 const [cfg,setCfg]=useState<Config|null>(null); const [page,setPage]=useState<'home'|'applications'|'submissions'|'settings'>('home');
 const [selected,setSelected]=useState('support'); const [saving,setSaving]=useState(false); const [notice,setNotice]=useState(''); const [error,setError]=useState(''); const [submissions,setSubmissions]=useState<Submission[]>([]); const [query,setQuery]=useState('');
 const notify=(m:string)=>{setNotice(m);setTimeout(()=>setNotice(''),2200)};
 async function load(){setError('');try{const [c,s]=await Promise.all([fetch(`${API}/config`),fetch(`${API}/submissions`)]);if(!c.ok)throw new Error('Bot dashboard API is offline. Start the bot first.');setCfg(await c.json());if(s.ok)setSubmissions(await s.json());}catch(e){setError(e instanceof Error?e.message:'Unable to load dashboard.');}}
 useEffect(()=>{load()},[]);
 async function save(next:Config){setSaving(true);setError('');try{const r=await fetch(`${API}/config`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});if(!r.ok)throw new Error(await r.text());setCfg(await r.json());notify('Saved to the live bot configuration.');}catch(e){setError(e instanceof Error?e.message:'Save failed.');}finally{setSaving(false)}}
 async function publish(){if(!cfg)return;const channelId=window.prompt('Discord channel ID to post the application panel in:');if(!channelId)return;setSaving(true);try{const r=await fetch(`${API}/publish-panel`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({channelId})});if(!r.ok)throw new Error(await r.text());notify('Panel posted to Discord.');}catch(e){setError(e instanceof Error?e.message:'Could not post panel.');}finally{setSaving(false)}}
 const filtered=submissions.filter(s=>`${s.id} ${s.username} ${s.type} ${s.status}`.toLowerCase().includes(query.toLowerCase()));
 if(!cfg) return <div className="center"><Cloud size={28}/><b>Relive</b><span>{error||'Connecting to the bot…'}</span><button className="primary" onClick={load}><RefreshCw size={15}/> Retry</button></div>;
 const current=cfg.applicationTypes.find(a=>a.id===selected)||cfg.applicationTypes[0];
 const nav=[['home','Overview',LayoutDashboard],['applications','Applications',ClipboardList],['submissions','Submissions',Inbox],['settings','Settings',Settings]] as const;
 const updateApp=(patch:Partial<AppType>)=>setCfg({...cfg,applicationTypes:cfg.applicationTypes.map(a=>a.id===current.id?{...a,...patch}:a)});
 const saveCurrent=()=>save(cfg);
 return <div className="app"><aside><div className="brand"><div className="logo"><Cloud size={19}/></div><div><strong>Relive</strong><small>Applications</small></div></div><div className="status"><i/> Bot connected</div><nav>{nav.map(([id,label,Icon])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><Icon size={16}/>{label}</button>)}</nav><div className="sidefoot">LOCAL CONTROL PANEL<br/><span>Bot + dashboard</span></div></aside><main><header><div><span className="eyebrow">Relive Control</span><h1>{page==='home'?'Overview':page[0].toUpperCase()+page.slice(1)}</h1></div><div className="headerActions"><Loading saving={saving}/><button className="iconbtn" onClick={load} title="Reload"><RefreshCw size={16}/></button><button className="primary" onClick={saveCurrent}><Save size={15}/> Save</button></div></header>
 {error&&<div className="error"><AlertCircle size={16}/>{error}</div>}
 {page==='home'&&<Home cfg={cfg} submissions={submissions} go={setPage} publish={publish}/>} 
 {page==='applications'&&<Applications cfg={cfg} current={current} selected={selected} setSelected={setSelected} updateApp={updateApp} setCfg={setCfg} save={save} notify={notify}/>} 
 {page==='submissions'&&<Submissions submissions={filtered} query={query} setQuery={setQuery}/>} 
 {page==='settings'&&<SettingsPage cfg={cfg} setCfg={setCfg}/>} 
 {notice&&<div className="toast"><CheckCircle2 size={16}/>{notice}</div>}
 </main></div>
}
function Home({cfg,submissions,go,publish}:{cfg:Config;submissions:Submission[];go:(p:any)=>void;publish:()=>void}){const pending=submissions.filter(s=>s.status==='Pending').length;return <section className="content"><div className="welcome"><div><span className="tag">● ONLINE</span><h2>Everything in one place.</h2><p>Configure applications here; applicants still complete everything privately in Discord DMs.</p><div className="actions"><button className="primary" onClick={publish}><Send size={15}/> Post panel</button><button className="secondary" onClick={()=>go('applications')}>Edit applications</button></div></div><div className="flow"><span>Panel</span><b>→</b><span>DMs</span><b>→</b><span>Review</span><b>→</b><span>Decision</span></div></div><div className="stats"><div><small>Total</small><strong>{submissions.length}</strong></div><div><small>Pending</small><strong>{pending}</strong></div><div><small>Accepted</small><strong>{submissions.filter(s=>s.status==='Accepted').length}</strong></div><div><small>Denied</small><strong>{submissions.filter(s=>s.status==='Denied').length}</strong></div><div><small>Types</small><strong>{cfg.applicationTypes.filter(a=>a.active).length}</strong></div></div><div className="grid2"><div className="card"><h3>Application types</h3>{cfg.applicationTypes.map(a=><div className="minirow" key={a.id}><span>{a.emoji}</span><div><b>{a.name}</b><small>{a.questions.length} questions</small></div><em className={a.active?'on':''}>{a.active?'Active':'Off'}</em></div>)}</div><div className="card"><h3>Review workflow</h3><p className="muted">Review decisions happen directly on each Discord application.</p><div className="decision"><b>✓ Accept</b><b>✓ Accept with Reason</b><b>× Deny</b><b>× Deny with Reason</b></div></div></div></section>}
function Applications({cfg,current,selected,setSelected,updateApp,setCfg,save,notify}:{cfg:Config;current:AppType;selected:string;setSelected:(s:string)=>void;updateApp:(p:Partial<AppType>)=>void;setCfg:(c:Config)=>void;save:(c:Config)=>void;notify:(s:string)=>void}){const add=()=>{const a=blankApp();setCfg({...cfg,applicationTypes:[...cfg.applicationTypes,a]});setSelected(a.id);notify('Application type added.');};const remove=()=>{if(!confirm(`Delete ${current.name}?`))return;const rest=cfg.applicationTypes.filter(a=>a.id!==current.id);setCfg({...cfg,applicationTypes:rest});setSelected(rest[0]?.id||'');notify('Application type removed.');};const q=(i:number,v:string)=>updateApp({questions:current.questions.map((x,n)=>n===i?v:x)});return <section className="content"><div className="appLayout"><div className="list card">{cfg.applicationTypes.map(a=><button className={a.id===selected?'appselect selected':'appselect'} onClick={()=>setSelected(a.id)} key={a.id}><span>{a.emoji}</span><div><b>{a.name}</b><small>{a.questions.length} questions</small></div><i className={a.active?'dot':''}/></button>)}<button className="addline" onClick={add}><Plus size={15}/> New type</button></div><div className="editor card"><div className="editorTop"><div><h2>{current.emoji} {current.name}</h2><p>These are the real questions the bot asks in DMs.</p></div><button className="danger" onClick={remove}><Trash2 size={15}/></button></div><div className="fields"><label>Name<input value={current.name} onChange={e=>updateApp({name:e.target.value})}/></label><label>Emoji<input value={current.emoji} onChange={e=>updateApp({emoji:e.target.value})}/></label><label className="wide">Description<textarea value={current.description} onChange={e=>updateApp({description:e.target.value})}/></label><label className="toggle"><input type="checkbox" checked={current.active} onChange={e=>updateApp({active:e.target.checked})}/> Enabled</label></div><div className="questionsHead"><div><h3>Questions</h3><small>Order matters. Every question is sent as a separate DM.</small></div><button className="secondary" onClick={()=>updateApp({questions:[...current.questions,'New question']})}><Plus size={14}/> Add</button></div>{current.questions.map((question,i)=><div className="qrow" key={i}><span>{i+1}</span><input value={question} onChange={e=>q(i,e.target.value)}/><button onClick={()=>updateApp({questions:current.questions.filter((_,n)=>n!==i)})}><Trash2 size={14}/></button></div>)}<button className="saveFull" onClick={()=>save(cfg)}><Save size={15}/> Save application type</button></div></div></section>}
function Submissions({submissions,query,setQuery}:{submissions:Submission[];query:string;setQuery:(s:string)=>void}){return <section className="content"><div className="search"><Search size={15}/><input placeholder="Search ID, applicant, type, status…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="card table"><div className="tableHead"><span>Application</span><span>Applicant</span><span>Type</span><span>Status</span><span>Date</span></div>{submissions.map(s=><div className="tableRow" key={s.id}><b>{s.id}</b><span>{s.username}</span><span>{s.type}</span><em className={s.status.toLowerCase().replaceAll(' ','-')}>{s.status}</em><span>{new Date(s.submittedAt).toLocaleDateString()}</span></div>)}{!submissions.length&&<div className="empty">No applications found.</div>}</div></section>}
function SettingsPage({cfg,setCfg}:{cfg:Config;setCfg:(c:Config)=>void}){return <section className="content"><div className="card settings"><h2>Discord settings</h2><p>These values are saved directly into the bot configuration.</p><div className="settingsgrid"><label>Panel title<input value={cfg.panel.title} onChange={e=>setCfg({...cfg,panel:{...cfg.panel,title:e.target.value}})}/></label><label>Review role ID<input value={cfg.reviewRoleId} onChange={e=>setCfg({...cfg,reviewRoleId:e.target.value})} placeholder="Discord role ID"/></label><label className="wide">Panel description<textarea value={cfg.panel.description} onChange={e=>setCfg({...cfg,panel:{...cfg.panel,description:e.target.value}})}/></label>{Object.keys(cfg.channels).map(k=><label key={k}>{k} submission channel ID<input value={cfg.channels[k]} onChange={e=>setCfg({...cfg,channels:{...cfg.channels,[k]:e.target.value}})} placeholder="Discord channel ID"/></label>)}</div><div className="messageBlock"><h3>DM messages</h3>{Object.entries(cfg.messages).map(([k,v])=><label key={k}>{k}<textarea value={v} onChange={e=>setCfg({...cfg,messages:{...cfg.messages,[k]:e.target.value}})}/></label>)}</div></div></section>}

createRoot(document.getElementById('root')!).render(<App/>);
